### PR TITLE
Update to v3.1.0

### PR DESCRIPTION
**Pull request by honnorat**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update to version 3.1.0

Closes #21

### CODE REVIEW

**Comment by honnorat** [comment]
Hi @djsutherland, would it be possible to merge this PR ?

Poke @ocefpaf @beckermr

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Comment by ocefpaf** [comment]
@honnorat do you want to add yourself as a maintainer here before we merge?

**Comment by honnorat** [comment]
Yes, done !

**Pull request merged**
